# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipe.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pipe.proto',
  package='pongpipe',
  serialized_pb=_b('\n\npipe.proto\x12\x08pongpipe\"+\n\tGameInput\x12\r\n\x05KeyUp\x18\x01 \x02(\x08\x12\x0f\n\x07KeyDown\x18\x02 \x02(\x08\"9\n\tGameState\",\n\x06Pixels\x12\x0b\n\x07paddle1\x10\x00\x12\x0b\n\x07paddle2\x10\x01\x12\x08\n\x04\x62\x61ll\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_GAMESTATE_PIXELS = _descriptor.EnumDescriptor(
  name='Pixels',
  full_name='pongpipe.GameState.Pixels',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='paddle1', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='paddle2', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ball', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=82,
  serialized_end=126,
)
_sym_db.RegisterEnumDescriptor(_GAMESTATE_PIXELS)


_GAMEINPUT = _descriptor.Descriptor(
  name='GameInput',
  full_name='pongpipe.GameInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='KeyUp', full_name='pongpipe.GameInput.KeyUp', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='KeyDown', full_name='pongpipe.GameInput.KeyDown', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=67,
)


_GAMESTATE = _descriptor.Descriptor(
  name='GameState',
  full_name='pongpipe.GameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GAMESTATE_PIXELS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=126,
)

_GAMESTATE_PIXELS.containing_type = _GAMESTATE
DESCRIPTOR.message_types_by_name['GameInput'] = _GAMEINPUT
DESCRIPTOR.message_types_by_name['GameState'] = _GAMESTATE

GameInput = _reflection.GeneratedProtocolMessageType('GameInput', (_message.Message,), dict(
  DESCRIPTOR = _GAMEINPUT,
  __module__ = 'pipe_pb2'
  # @@protoc_insertion_point(class_scope:pongpipe.GameInput)
  ))
_sym_db.RegisterMessage(GameInput)

GameState = _reflection.GeneratedProtocolMessageType('GameState', (_message.Message,), dict(
  DESCRIPTOR = _GAMESTATE,
  __module__ = 'pipe_pb2'
  # @@protoc_insertion_point(class_scope:pongpipe.GameState)
  ))
_sym_db.RegisterMessage(GameState)


# @@protoc_insertion_point(module_scope)
