// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pipe.proto

#ifndef PROTOBUF_pipe_2eproto__INCLUDED
#define PROTOBUF_pipe_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pongpipe {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pipe_2eproto();
void protobuf_AssignDesc_pipe_2eproto();
void protobuf_ShutdownFile_pipe_2eproto();

class GameInput;
class GameState;

enum GameState_Pixels {
  GameState_Pixels_empty = 0,
  GameState_Pixels_paddle0 = 1,
  GameState_Pixels_paddle1 = 2,
  GameState_Pixels_ball = 3
};
bool GameState_Pixels_IsValid(int value);
const GameState_Pixels GameState_Pixels_Pixels_MIN = GameState_Pixels_empty;
const GameState_Pixels GameState_Pixels_Pixels_MAX = GameState_Pixels_ball;
const int GameState_Pixels_Pixels_ARRAYSIZE = GameState_Pixels_Pixels_MAX + 1;

const ::google::protobuf::EnumDescriptor* GameState_Pixels_descriptor();
inline const ::std::string& GameState_Pixels_Name(GameState_Pixels value) {
  return ::google::protobuf::internal::NameOfEnum(
    GameState_Pixels_descriptor(), value);
}
inline bool GameState_Pixels_Parse(
    const ::std::string& name, GameState_Pixels* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GameState_Pixels>(
    GameState_Pixels_descriptor(), name, value);
}
// ===================================================================

class GameInput : public ::google::protobuf::Message {
 public:
  GameInput();
  virtual ~GameInput();

  GameInput(const GameInput& from);

  inline GameInput& operator=(const GameInput& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GameInput& default_instance();

  void Swap(GameInput* other);

  // implements Message ----------------------------------------------

  GameInput* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameInput& from);
  void MergeFrom(const GameInput& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool KeyUp = 1;
  inline bool has_keyup() const;
  inline void clear_keyup();
  static const int kKeyUpFieldNumber = 1;
  inline bool keyup() const;
  inline void set_keyup(bool value);

  // required bool KeyDown = 2;
  inline bool has_keydown() const;
  inline void clear_keydown();
  static const int kKeyDownFieldNumber = 2;
  inline bool keydown() const;
  inline void set_keydown(bool value);

  // @@protoc_insertion_point(class_scope:pongpipe.GameInput)
 private:
  inline void set_has_keyup();
  inline void clear_has_keyup();
  inline void set_has_keydown();
  inline void clear_has_keydown();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  bool keyup_;
  bool keydown_;
  friend void  protobuf_AddDesc_pipe_2eproto();
  friend void protobuf_AssignDesc_pipe_2eproto();
  friend void protobuf_ShutdownFile_pipe_2eproto();

  void InitAsDefaultInstance();
  static GameInput* default_instance_;
};
// -------------------------------------------------------------------

class GameState : public ::google::protobuf::Message {
 public:
  GameState();
  virtual ~GameState();

  GameState(const GameState& from);

  inline GameState& operator=(const GameState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GameState& default_instance();

  void Swap(GameState* other);

  // implements Message ----------------------------------------------

  GameState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameState& from);
  void MergeFrom(const GameState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef GameState_Pixels Pixels;
  static const Pixels empty = GameState_Pixels_empty;
  static const Pixels paddle0 = GameState_Pixels_paddle0;
  static const Pixels paddle1 = GameState_Pixels_paddle1;
  static const Pixels ball = GameState_Pixels_ball;
  static inline bool Pixels_IsValid(int value) {
    return GameState_Pixels_IsValid(value);
  }
  static const Pixels Pixels_MIN =
    GameState_Pixels_Pixels_MIN;
  static const Pixels Pixels_MAX =
    GameState_Pixels_Pixels_MAX;
  static const int Pixels_ARRAYSIZE =
    GameState_Pixels_Pixels_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Pixels_descriptor() {
    return GameState_Pixels_descriptor();
  }
  static inline const ::std::string& Pixels_Name(Pixels value) {
    return GameState_Pixels_Name(value);
  }
  static inline bool Pixels_Parse(const ::std::string& name,
      Pixels* value) {
    return GameState_Pixels_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .pongpipe.GameState.Pixels board = 1 [packed = true];
  inline int board_size() const;
  inline void clear_board();
  static const int kBoardFieldNumber = 1;
  inline ::pongpipe::GameState_Pixels board(int index) const;
  inline void set_board(int index, ::pongpipe::GameState_Pixels value);
  inline void add_board(::pongpipe::GameState_Pixels value);
  inline const ::google::protobuf::RepeatedField<int>& board() const;
  inline ::google::protobuf::RepeatedField<int>* mutable_board();

  // @@protoc_insertion_point(class_scope:pongpipe.GameState)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField<int> board_;
  mutable int _board_cached_byte_size_;
  friend void  protobuf_AddDesc_pipe_2eproto();
  friend void protobuf_AssignDesc_pipe_2eproto();
  friend void protobuf_ShutdownFile_pipe_2eproto();

  void InitAsDefaultInstance();
  static GameState* default_instance_;
};
// ===================================================================


// ===================================================================

// GameInput

// required bool KeyUp = 1;
inline bool GameInput::has_keyup() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GameInput::set_has_keyup() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GameInput::clear_has_keyup() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GameInput::clear_keyup() {
  keyup_ = false;
  clear_has_keyup();
}
inline bool GameInput::keyup() const {
  // @@protoc_insertion_point(field_get:pongpipe.GameInput.KeyUp)
  return keyup_;
}
inline void GameInput::set_keyup(bool value) {
  set_has_keyup();
  keyup_ = value;
  // @@protoc_insertion_point(field_set:pongpipe.GameInput.KeyUp)
}

// required bool KeyDown = 2;
inline bool GameInput::has_keydown() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GameInput::set_has_keydown() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GameInput::clear_has_keydown() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GameInput::clear_keydown() {
  keydown_ = false;
  clear_has_keydown();
}
inline bool GameInput::keydown() const {
  // @@protoc_insertion_point(field_get:pongpipe.GameInput.KeyDown)
  return keydown_;
}
inline void GameInput::set_keydown(bool value) {
  set_has_keydown();
  keydown_ = value;
  // @@protoc_insertion_point(field_set:pongpipe.GameInput.KeyDown)
}

// -------------------------------------------------------------------

// GameState

// repeated .pongpipe.GameState.Pixels board = 1 [packed = true];
inline int GameState::board_size() const {
  return board_.size();
}
inline void GameState::clear_board() {
  board_.Clear();
}
inline ::pongpipe::GameState_Pixels GameState::board(int index) const {
  // @@protoc_insertion_point(field_get:pongpipe.GameState.board)
  return static_cast< ::pongpipe::GameState_Pixels >(board_.Get(index));
}
inline void GameState::set_board(int index, ::pongpipe::GameState_Pixels value) {
  assert(::pongpipe::GameState_Pixels_IsValid(value));
  board_.Set(index, value);
  // @@protoc_insertion_point(field_set:pongpipe.GameState.board)
}
inline void GameState::add_board(::pongpipe::GameState_Pixels value) {
  assert(::pongpipe::GameState_Pixels_IsValid(value));
  board_.Add(value);
  // @@protoc_insertion_point(field_add:pongpipe.GameState.board)
}
inline const ::google::protobuf::RepeatedField<int>&
GameState::board() const {
  // @@protoc_insertion_point(field_list:pongpipe.GameState.board)
  return board_;
}
inline ::google::protobuf::RepeatedField<int>*
GameState::mutable_board() {
  // @@protoc_insertion_point(field_mutable_list:pongpipe.GameState.board)
  return &board_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pongpipe

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::pongpipe::GameState_Pixels> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pongpipe::GameState_Pixels>() {
  return ::pongpipe::GameState_Pixels_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pipe_2eproto__INCLUDED
